### ISSUE TITLE
Newer versions of packages don't work

### ISSUE THREAD

**Issue by nandorojo** [val-town/deno-http-worker#19]
I'll put together a reproduction here soon, but I just wanted to jot this down first.

Imagine you're importing an npm package like this:

```ts
const code = `await import('npm:some-npm-package@0.0.3')`

// ...run the worker below with that code
```

Next, you publish a new version of `some-npm-package` to NPM under `0.0.4`.

So you edit the code like so:

```ts
const code = `await import('npm:some-npm-package@0.0.4')`

// ...run the worker below with that code
```

However, Deno throws an error saying that version doesn't exist. 

## Workaround

You need to open the CLI, type `'deno'`, hit `Enter`, run the import code (`await import('npm:some-npm-package@0.0.4')`), hit enter, and it'll download it. Only then, after restarting the worker, can you use the new version of the package.

It seems like the worker uses some sort of deno cache and won't fetch newer versions of packages. Any ideas? 

If you need a full reproduction, definitely let me know. It should be easy to get together.

**Comment by maxmcd** [comment]
@nandorojo I wonder if it's this issue: https://github.com/denoland/deno/issues/23965

Might be fixed by changing it to a non-dynamic import.

**Comment by nandorojo** [comment]
Good point, let me make a comparison repro between JSR and NPM.

Thanks for sharing the linked issue, I'll try to dig in further.

**Comment by maxmcd** [comment]
Hey @nandorojo, I think this is fully resolved in the latest Deno. Going to close, but pls reopen if I'm wrong!

**Comment by nandorojo** [comment]
Cool!
